### PR TITLE
Factory Girl movement.

### PR DESCRIPTION
**Pull request by Calvyn82**
This one should be better. I moved the files over and ran rubocop against my changes.

### CODE REVIEW

**Comment by tsujigiri** [comment]
I'm sorry if this hound thing is all too annoying. In generall it helps keeping the code clean, but I can see that it might also be off-putting to new contributors.

**Comment by Calvyn82** [comment]
It's fine. I'm just happy to get to be helping out on such a cool project.

**Comment by tsujigiri** [comment]
:+1:

**Comment by gedankenstuecke** [comment]
👍 awesome!

**Pull request merged**
