### PR TITLE
Moved Factories and deleted redundancies

### PR DESCRIPTION
**Pull request by Calvyn82**
The tests should work fine now.

### CODE REVIEW

**Comment by Calvyn82** [comment]
Do I need to go make houndci happy?

**Comment by tsujigiri** [comment]
It is much appreciated for sake of consistency. :)

**Comment by tsujigiri** [comment]
Looks great otherwise! Thanks a lot!

**Comment by Calvyn82** [comment]
There a way to check hound locally before opening a pull request?

**Comment by tsujigiri** [comment]
If you install the `rubocop` gem, you should be able to run `rubocop spec/factories` locally to see if it is satisfied. And you don't need to open a pull-request if you want to update it. You can just push to the same branch and the PR will be updated automatically. Force-pushing works as well.

**Comment by Calvyn82** [comment]
I installed and ran it against that last pull request. I'll do it on all of my future commits.

Sorry about the pull request thing. If it isn't obvious, I'm still pretty new to all of this. Only been coding at all for about year, and this is only the second time I've submitted to a project I'm not a contributor on.

**Comment by tsujigiri** [comment]
Don't worry at all! I totally agree that it's not obvious.

**Pull request closed without merging**
