### PR TITLE
added first CoC draft

### PR DESCRIPTION
**Pull request by gedankenstuecke**
This could be a fix for issue #237. Directly modified from slidewinder.

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
Uh, has someone an idea why this test fails now? :confused:

**Comment by gedankenstuecke** [comment]
Ok, so just rerunning it worked in the end :recycle:

**Comment by gedankenstuecke** [comment]
I talked to Kay during the Working Open Workshop and she agreed to be the external person people can talk to if any of us is the issue. :+1:

**Comment by Blahah** [comment]
:+1: great issue!

**Comment by philippbayer** [comment]
I think the tests still fail due to seeds sometimes not properly loading, so that achievements are missing and the relevant tests crash - it's a bit weird and I haven't yet figured out why that happens

The text itself looks good to me; we may need one more "external" person at some point, but I think that our community isn't large enough to warrant that right now.

+1 for merge

**Comment by gedankenstuecke** [comment]
Just rerunning it worked though, so that might not be the issue with the tests. 

Regarding a second external person: I think that's fine for now. Once we're larger we can get another person of authority. :smile: :+1:

**Pull request merged**
